// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvJinbwIMfjVHK3YStkbnM41hUkEcQDM',
    appId: '1:743483025850:web:326cf2722c95afcf539583',
    messagingSenderId: '743483025850',
    projectId: 'babyshopnew-689d7',
    authDomain: 'babyshopnew-689d7.firebaseapp.com',
    storageBucket: 'babyshopnew-689d7.firebasestorage.app',
    measurementId: 'G-KL851H524X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fSz3bqeAe6SXSqnK0zYaehJU6MHWbSE',
    appId: '1:743483025850:android:2f7a56353e5c9b84539583',
    messagingSenderId: '743483025850',
    projectId: 'babyshopnew-689d7',
    storageBucket: 'babyshopnew-689d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOMsj8w-KjkOhGQBScwj3bzVNELdfar3c',
    appId: '1:743483025850:ios:29afb43f1a601b11539583',
    messagingSenderId: '743483025850',
    projectId: 'babyshopnew-689d7',
    storageBucket: 'babyshopnew-689d7.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOMsj8w-KjkOhGQBScwj3bzVNELdfar3c',
    appId: '1:743483025850:ios:29afb43f1a601b11539583',
    messagingSenderId: '743483025850',
    projectId: 'babyshopnew-689d7',
    storageBucket: 'babyshopnew-689d7.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvJinbwIMfjVHK3YStkbnM41hUkEcQDM',
    appId: '1:743483025850:web:f4b259e5ebc9818e539583',
    messagingSenderId: '743483025850',
    projectId: 'babyshopnew-689d7',
    authDomain: 'babyshopnew-689d7.firebaseapp.com',
    storageBucket: 'babyshopnew-689d7.firebasestorage.app',
    measurementId: 'G-NCNE6RR7Z1',
  );
}
