// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO9gDtAolAYrWr4HpIGoWU7u25ycCAyqQ',
    appId: '1:901846426479:web:81927d1287abc4dac33e9a',
    messagingSenderId: '901846426479',
    projectId: 'babyshop-b4cfe',
    authDomain: 'babyshop-b4cfe.firebaseapp.com',
    storageBucket: 'babyshop-b4cfe.firebasestorage.app',
    measurementId: 'G-CDFB3WX59D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCLEueiAux944eadxb_U2Dpgyrgkf6SQ',
    appId: '1:901846426479:android:add03b86a0bd7758c33e9a',
    messagingSenderId: '901846426479',
    projectId: 'babyshop-b4cfe',
    storageBucket: 'babyshop-b4cfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBJGE0mr62ri4rcIha5dF0YWXM0-NGnA',
    appId: '1:901846426479:ios:b0381b3b90be5908c33e9a',
    messagingSenderId: '901846426479',
    projectId: 'babyshop-b4cfe',
    storageBucket: 'babyshop-b4cfe.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjBJGE0mr62ri4rcIha5dF0YWXM0-NGnA',
    appId: '1:901846426479:ios:b0381b3b90be5908c33e9a',
    messagingSenderId: '901846426479',
    projectId: 'babyshop-b4cfe',
    storageBucket: 'babyshop-b4cfe.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO9gDtAolAYrWr4HpIGoWU7u25ycCAyqQ',
    appId: '1:901846426479:web:2aac927e1ef5e7d8c33e9a',
    messagingSenderId: '901846426479',
    projectId: 'babyshop-b4cfe',
    authDomain: 'babyshop-b4cfe.firebaseapp.com',
    storageBucket: 'babyshop-b4cfe.firebasestorage.app',
    measurementId: 'G-67MBPKFBR0',
  );
}
